name: 'Doxygen Action'
description: 'Generate documentation on a commented project using doxygen'
branding:
  icon: 'book-open'
  color: 'gray-dark'
inputs:
  doxyfile-path:
    description: 'Path to Doxyfile'
    required: true
    default: './Doxyfile'
  working-directory:
    description: 'Working directory'
    required: true
    default: '.'
  enable-latex:
    description: 'Generate latex documentation'
    required: false
    default: false
  fail-on-warnings:
    description: 'Make this action fail if doxygen produces warnings.'
    required: false
    default: 'FALSE'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.doxyfile-path }}
    - ${{ inputs.working-directory }}
    - ${{ inputs.enable-latex }}
    - ${{ inputs.fail-on-warnings }}
